name: Android Release

on:
  pull_request:
    paths:
      - app-k9/.github/workflow/release.yml
      - app-k9/build.gradle.kts
    branches: [main]
  push:
    paths:
      - app-k9/build.gradle.kts
    branches:
      - main  # or 'release' if that's your release branch

jobs:
  build-and-release:
    runs-on: SJSU-office
    environment: Android Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Maven to use GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>github-actions[bot]</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Get version name
        id: version
        run: |
              VERSION_NAME=$(grep appVersionName app-k9mail/build.gradle.kts | sed "s/.*'\(.*\)'.*/\1/")
              VERSION_NAME=${VERSION_NAME%%_*}
              VERSION_NAME="${VERSION_NAME}_$(git rev-parse --short HEAD)"
              sed -i "s/appVersionName \?= \?['\"].*['\"]/appVersionName = '${VERSION_NAME}'/" app-k9mail/build.gradle.kts
              echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Build release APK and AAB
        run: |
          KEYFILE=${PWD}/signing-key.jks
          echo "${{ secrets.DDD_KEYFILE }}" | base64 -d > $KEYFILE
          echo "populated $KEYFILE"
          ./gradlew clean :app-k9mail:bundleRelease :app-k9mail:assembleRelease  \
              -Pk9.release.storeFile=$KEYFILE \
              -Pk9.release.storePassword=$DDD_KEYFILE_PASSWORD \
              -Pk9.release.keyAlias=ddd \
              -Pk9.release.keyPassword=$DDD_KEYFILE_PASSWORD
          # rename the files so that the names are reasonable
          mv app-k9mail/build/outputs/apk/release/app-k9mail-release.apk ddd-mail.apk
        env:
          DDD_KEYFILE_PASSWORD: ${{ secrets.DDD_KEYFILE_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION_NAME }}
          name: Release v${{ steps.version.outputs.VERSION_NAME }}
          draft: false
          prerelease: false
          files: |
                ddd-mail.apk
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

